# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
   name: Default
   demands:
    - agent.name -equals mcbride-mac-mini

steps:
- task: DownloadSecureFile@1
  inputs:
    secureFile: ‘.env.test’
- task: CopyFiles@2
  inputs:
    SourceFolder: $(Agent.TempDirectory)
    Contents: ‘**\.env.test’
    TargetFolder: $(Build.SourcesDirectory)
  displayName: 'pytest'
- script: |
    python3 -m pip install --upgrade pip
    python3 -m pip install pip-tools
    python3 -m piptools compile
    pip install -r requirements.txt
    pytest

