# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
    pip install -r requirements.txt
  displayName: 'Run a one-line script'

- script: |
    python -m pytest tests/
  displayName: 'pytest'
