# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script:
    python3 -m pip install --upgrade pip
    python3 -m pip install pip-tools
    python3 -m piptools compile
    pip install -r requirements.txt
    pytest
  displayName: 'pytest'
