# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: 
   name: Default
   demands:
    - agent.name -equals mcbride-mac-mini

variables:
  IMAGE_REGISTRY_CONNECTION: 'CUPE Jobs Container Registry'
  IMAGE_REGISTRY: 'CUPE Jobs Repository'
  IMAGE_REPOSITORY: 'adodemo.azurecr.io'
  TAG: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build stage
  jobs:
  - job: BuildJob
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: '$(python.version)'
      displayName: 'Use Python $(python.version)'
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env.test'
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.TempDirectory)
        Contents: '**\.env.test'
        TargetFolder: $(Build.SourcesDirectory)
      displayName: 'pytest'
    - script: |
        python3 -m pip install --upgrade pip
        python3 -m pip install pip-tools
        python3 -m piptools compile
        pip install -r requirements.txt
        pytest  

# - stage: Docker
#   displayName: Docker stage 
#   jobs:
#   - job: DockerPushImage
#     steps:
#     - task: Docker@2
#       inputs:
#         containerRegistry: '$(IMAGE_REGISTRY_CONNECTION)'
#         repository: '$(IMAGE_REPOSITORY)'
#         command: 'buildAndPush'
#         Dockerfile: '**/Dockerfile'
#         tags: '$(TAG)'
