# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: 'cb4d46bf-14c3-49f3-85bf-56bb795ff580'
  imageRepository: 'sunilyorkcupejobsrenewapi'
  containerRegistry: 'sunilmanikonregistry.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  
  # Python version: 3.10.9
  pythonVersion: '3.10.9'
  
  tag: '$(Build.BuildId)'

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

pool:
  vmImage: $(vmImageName)

stages: 
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    steps:
    - task: UsePythonVersion@0
      inputs:
        versionSpec: $(pythonVersion)
      displayName: 'Use Python $(pythonVersion)'
      
    - script: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      displayName: 'Install dependencies'

    - script: |
        black --check .
        flake8 .
      displayName: 'Linting - Style guide enforcement'
    
    - task: DownloadSecureFile@1
      inputs:
        secureFile: '.env.test'
    - task: CopyFiles@2
      inputs:
        SourceFolder: $(Agent.TempDirectory)
        Contents: '**\.env.test'
        TargetFolder: $(Build.SourcesDirectory)
      displayName: 'Load .env.test'
  
    - script: |
        pip install pytest pytest-mock pytest-azurepipelines
        pytest
      displayName: 'pytest'
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)

